# Use postgres/example user/password credentials
#version: '3.1'

#services:

 # db:
#    image: postgres:12-alpine
 #   restart: always
  #  ports:
  #     - 3306:3306
#    volumes:
 #     - ./data:/var/lib/postgresql
  #  environment:
   #   - POSTGRES_DB=db
    #  - POSTGRES_USER=admin
     # - POSTGRES_PASSWORD=mypassword


version: '3.7'
services:
  postgresql:
    image: postgres:12-alpine
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgresql
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
